---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: proxius-webhook-service
      namespace: proxius-system
      path: /mutate-webhooks-igordc-com-v1-proxydef
  failurePolicy: Fail
  name: mproxydef.kb.io
  rules:
  - apiGroups:
    - webhooks.igordc.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - proxydefs
  sideEffects: None
