# permissions for end users to edit proxydefs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: proxydef-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: proxius
    app.kubernetes.io/part-of: proxius
    app.kubernetes.io/managed-by: kustomize
  name: proxydef-editor-role
rules:
- apiGroups:
  - proxy.igordc.com
  resources:
  - proxydefs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.igordc.com
  resources:
  - proxydefs/status
  verbs:
  - get
