---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - proxy.igordc.com
  resources:
  - proxydefs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.igordc.com
  resources:
  - proxydefs/finalizers
  verbs:
  - update
- apiGroups:
  - proxy.igordc.com
  resources:
  - proxydefs/status
  verbs:
  - get
  - patch
  - update
